# Base node image
FROM node:20-alpine AS base
WORKDIR /app
RUN npm install -g turbo

# Prune step
FROM base AS pruner
COPY . .
RUN turbo prune storefront --out=json-out

# Install dependencies step
FROM base AS installer
COPY --from=pruner /app/json-out/json/ .
COPY --from=pruner /app/json-out/package-lock.json ./package-lock.json
RUN npm clean-install

# Build step
FROM base AS builder
COPY --from=installer /app/ .
COPY --from=pruner /app/json-out/full/ .
RUN npx turbo run build --filter=storefront...

# Runner step
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/apps/storefront/public ./apps/storefront/public
COPY --from=builder --chown=nextjs:nodejs /app/apps/storefront/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/storefront/.next/static ./apps/storefront/.next/static

USER nextjs
EXPOSE 3000
ENV PORT=3000
CMD ["node", "apps/storefront/server.js"]
